steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: 'build'
    args:
      - 'build'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:$COMMIT_SHA'
      - '-t'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:latest'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: 'push'
    args:
      - 'push'
      - '--all-tags'
      - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME'

images:
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:$COMMIT_SHA'
  - '${_AR_REGION}-docker.pkg.dev/$PROJECT_ID/cloud-run-images/$_SERVICE_NAME:latest'

substitutions:
  _SERVICE_NAME: 'CAMBIAR-antes-de-usar'  # se sobreescribe vía --substitutions en el trigger (ticket2)
  _AR_REGION: 'CAMBIAR-antes-de-usar'     # se sobreescribe vía --substitutions en el trigger (ticket2)

options:
  logging: CLOUD_LOGGING_ONLY